[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
gear_protocol = "Ders6v6yfeAN2WVXUoNZbQ778YxTLe3dF4tBBo4dURDo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/{YOUR_PATH}/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
