[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
gear_protocol = "9kFWw3AnZXiTAgj3Les4sxGxmMmFLPQH79NGwZ32GSvP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/KyrieLi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
